# Generated by Django 4.0 on 2021-12-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='game',
            name='year_published',
        ),
    ]
