# Generated by Django 4.0 on 2021-12-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
