# Generated by Django 4.0 on 2021-12-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_game_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='my_loan',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='unfinished',
        ),
        migrations.AddField(
            model_name='loan',
            name='action',
            field=models.CharField(blank=True, choices=[('r', 'Reserve'), ('l', 'Loan Out'), ('r', 'Return')], default='r', help_text='Loan action', max_length=1),
        ),
    ]
